### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by nonsoiwedinobi** [nonsoiwedinobi/what2watch#6]
User story:

- [x] As a user landing on the What2Watch homepage, I want to be captivated by an engaging hero section featuring visually striking images of various movies, creating a compelling atmosphere that encourages me to explore and search for films.

Acceptance Criteria:

- [x] Visually appealing
- [x] Use of high quality images
- [x] Responsive 
- [x] When scrolling past Hero section there should be a smooth transition or fade

**Comment by IlhanDuale** [comment]
User story:

- [ ] As a user landing on the What2Watch homepage, I want to be captivated by an engaging hero section featuring visually striking images of various movies, creating a compelling atmosphere that encourages me to explore and search for films.

Acceptance Criteria:

- [ ] Visually appealing
- [ ] Use of high quality images
- [ ] Responsive 
- [ ] When scrolling past Hero section there should be a smooth transition or fade
